-- initial amazon table
-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);



-- paper research platform table
-- paper table
CREATE TABLE papers (
    pid INT NOT NULL PRIMARY KEY,
    title TEXT CHECK (length(title) <= 500),
    year INT,
    conference TEXT CHECK (length(conference) <= 500)
);

-- citation relationship among papers
CREATE TABLE citation (
	pid INT NOT NULL,
    cite_pid INT NOT NULL,
    PRIMARY KEY (pid, cite_pid)
);

-- authorship
CREATE TABLE authorship (
    pid INT,
    author TEXT
);

-- abstract
CREATE TABLE abstract (
    pid INT NOT NULL PRIMARY KEY,
    abstract TEXT
);

-- data for user authentication (registration & login)
CREATE TABLE auth (
	uid INT NOT NULL PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    school VARCHAR(255) NOT NULL
);

-- notice: 'user' is a reserved word in Postgres, which means if you use user as the table name, you will have an error
-- data for user profile & dashboard
CREATE TABLE user_info (
	uid INT NOT NULL PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
    nickname VARCHAR(255) UNIQUE NOT NULL,
    citenum INT DEFAULT 0, 
    research_interest VARCHAR(255)
);

-- user citation cart
CREATE TABLE user_cart (
	uid INT NOT NULL,
    cite_pid INT NOT NULL,
    time_added timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

-- user browser history of papers
CREATE TABLE user_browse (
	uid INT NOT NULL,
	browsed_pid INT NOT NULL,
    time_browsed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

 
-- user’s collection
CREATE TABLE collections(
    uid INT NOT NULL,	
	collection_name VARCHAR(255) UNIQUE NOT NULL,
	pid INT NOT NULL
)

